[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install --production=false",
  "cd server && npm install --production=false",
  "cd ../client && npm install --production=false",
  "cd .."
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
