version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--no-deprecation
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL (opcional - para produção)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: checklist_financeiro
  #     POSTGRES_USER: checklist_user
  #     POSTGRES_PASSWORD: checklist_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

volumes:
  postgres_data:
