[build]
builder = "nixpacks"
buildCommand = "chmod +x scripts/build-production.sh && ./scripts/build-production.sh"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_OPTIONS = "--no-deprecation"
NODE_ENV = "production"
PORT = "3001"

# Configurações de build personalizadas
[build.envs]
NODE_ENV = "production"
